### ISSUE TITLE
Use git-submodules to include SafeMath and Organized contracts in openst-contracts

### ISSUE THREAD

**Issue by deepesh-kn** [OpenSTFoundation/openst-contracts#197]
**Use git-submodules to include the following contracts**

- SafeMath.sol
- Organized.sol

**Following is the proposal:**
1. Remove the existing implementation of the above contracts.
2. Use git-submodules to include Organized contract in the project from `OpenST/organization-contracts`.
3.  Use git-submodules to include SafeMath contract in the project from < will be updated >

**Comment by 0xsarvesh** [comment]
@deepesh-kn  `SafeMath.sol` is owned by openzeppelin . See [here](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/math/SafeMath.sol)

They also have published npm. See [here](https://www.npmjs.com/package/openzeppelin-solidity) 

**Questions:**
1. is openzeppelin correct source for safemath for this ticket? 
2. Why do you prefer git-submodule instead of npm for this?

**Comment by deepesh-kn** [comment]
> @deepesh-kn `SafeMath.sol` is owned for openzeppelin . See [here](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/math/SafeMath.sol)
> 
> They also have published npm. See [here](https://www.npmjs.com/package/openzeppelin-solidity)
> 
> **Questions:**
> 
> 1. is openzeppelin correct source for safemath for this ticket?

Yes, openzeppelin is the correct source for safemath. 

> 2. Why do you prefer git-submodule instead of npm for this?

I am open for the discussion here. We have already used git-submodules in other repo so it was suggested here. We can use NPM for this. @pgev, you have done the research on git-submodule vs NPM and used git-submodules in one of the repo. What is your opinion here to use NPM?

**Comment by 0xsarvesh** [comment]
I would choose the npm package instead of git-submodule for dependency in this case. 

Reasoning: We can selectively import contracts like `safemath.sol` in npm package on the flip side all the contracts files will be pulled into the repository with git-submodule. With this reasoning, the npm package approach seems cleaner. 

Thoughts? @deepesh-kn  @schemar @pgev

**Comment by schemar** [comment]
> I would choose the npm package instead of git-submodule for dependency in this case.
> 
> Reasoning: We can selectively import contracts like `safemath.sol` in npm package on the flip side all the contracts files will be pulled into the repository with git-submodule. With this reasoning, the npm package approach seems cleaner.
> 
> Thoughts? @deepesh-kn @schemar @pgev

Please note that only a *reference* to the other repo is stored in our repo (upstream) in case of git submodules. It gets only expanded locally on the dev machines.

However, if we cannot find a way to pin specific tags with git submodules, they are not an option in my opinion. We need to be able to select versions of our dependencies.
@sarvesh-ost can you find out if you can specify a specific tag in the `.gitsubmodules` file so that everyone would clone that specific tag? Selecting just a branch (e.g. `master`) I would deem insufficient.
